#!/usr/bin/env bash
# This script extends previous exercise command and displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process

./1-list_your_processes | grep "bash"
